### ISSUE TITLE
bertini installation problem: BertiniSource

### ISSUE THREAD

**Issue by BestGerne** [ofloveandhate/bertini_real#47]
Hi,
I am currently installing bertini_real and am facing the following problem with BertiniSource:
![bertini_problem](https://user-images.githubusercontent.com/37087626/37309906-addbbf5a-2642-11e8-883f-9aeec4a783af.png)
Can you help me? Thank you!

**Comment by ofloveandhate** [comment]
install *flex* and *bison* from your package manager

**Comment by BestGerne** [comment]
It works! Thank you.

**Comment by ofloveandhate** [comment]
@BestGerne  as a future tip: post text, not screencap of text, so other people with the same problem will be able to find it in a search
