### ISSUE TITLE
Wrong Homology Output

### ISSUE THREAD

**Issue by tjstrunk** [ofloveandhate/bertini_real#49]
#1: I tried using bertini_real + polyTop to get me some homology of things like the variety corresponding to x^2 + y^2 + z^2 + w^2 - 1, f(x,y,z,w) where f is a random degree 3 homogeneous polynomial in x y z w, i.e. a random cubic surface living on S^3, something which should have at most 3 components, all of which contribute 1 to the rank of H^2. Aaaaand polyTop was giving me three components but rank 2 for H^2, which...lies. Cannot be so. So I went to check the torus example given here: http://www.bertinireal.com/gallery.html

#2: The torus example didn't go well. The first time I attempted it, literally just copy-pasting what's in the gallery to an input file, running bertini input, bertini_real, gather_br_samples in matlab, then polyTop in matlab, I got like rank 3 for H^1, rank 1 for H^0, and nothing for H^2 :/ Then I scraped everything, re-downloaded gather_br_samples (as I think that's where the issue is), and ran it again. And...somehow got more genus (rank of H^1) but still no H^2 at all.

I then tried just running some of polyTop in the command line. For face 1 of BRinfo, I tried checking out the left_points and right_points, only to find that they were empty... I did this after running all of polyTop in the command line, too, and still got empty matrices for left_points and right_points.

I'm thinking there's some issue in the gather_br_samples.m code but don't really know what happens under the hood with bertini real. (While waiting for responses, I'll be delving into that and seeing what I can 
see.)

**Comment by ofloveandhate** [comment]
there is probably not a problem in the gather functionality, but it is possible.  more likely is an incorrect decomposition.  can you please attach or inset here as code the input file you used?  also, try running `bertini_real_plotter` to visualize, and insert a pic here.  my guess is that something went wrong during decomposition.

**Comment by tjstrunk** [comment]
Yeah after checking out the code for the gather function last night, I'm thinking you're probably right.

I copy-pasted the input file from here the bertini_real gallery on the site:
```
CONFIG
tracktype: 1;
END;

INPUT
constant R, r;
R = 2;
r = 0.5;
variable_group x, y, z;
function f1;
f1 = (x^2+y^2+z^2+R^2 - r^2)^2 - 4*R^2*(x^2+y^2);
END;
```

Going to try `bertini_real_plotter` now, but I'm thinking you're right that something went wrong during decomposition. (I'm not sure what might have went wrong :/ )

**Comment by tjstrunk** [comment]
The file from bertini_real_plotter certainly _looks_ like a torus. I tried doing all this with sampler, too.
![br_troubleshooting](https://user-images.githubusercontent.com/10812544/38940987-c83f9d90-42e8-11e8-91ae-ba0db9a5307a.png)

Perhaps there is a problem with my settings for Javaplex or just polyTop then?

**Comment by ofloveandhate** [comment]
pushing the save button from bertini_real_plotter's window should save a surface as a png, and auto-title it the name of the working folder.

**Comment by ofloveandhate** [comment]
that decomposition is incorrect.

**Comment by ofloveandhate** [comment]
my suggestion is to increase `sharpendigits`, decrease both `tracktol___`s, and use the cauchy endgame `endgamenum: 2`.  that's a start at least.  in the end, i typically modify like 10-15 settings to get good decompositions.

**Comment by ofloveandhate** [comment]
simply re-running the decomposition may also solve the problem, unless you have `randomseed` specified.

**Comment by tjstrunk** [comment]
I ran the decomposition a few times and was still getting problems. However, setting

```
tracktolbeforeeg: 1e-9;
tracktolduringeg: 1e-10;
endgamenum: 2;
```

worked just fine for the torus.

However, I used the same settings on one of the random surfaces I'm studying, and it seems to have stumbled on another issue. Running bertini_real_plotter gives the error

```
undefined function or variable 'inputsdlg'
```

and polyTop does not assign all the values in the code so that it returns an error along the lines of 'b0 was not assigned during call to polyTop.'
The surface is supposed to be a smooth surface lying in S^3. It has multiple (as many as three) connected components; would the multiple components cause an issue for polyTop, bertini_real_plotter, or bertini_real?

There is more detail to the error in bertini_real_plotter above. Apparently the calling sequence goes like this:

```
bertini_real_plotter (line 100) -> load (line 128) -> get_indices (line 6) -> complicated_set_ind (line 22) -> get_user_indices (line 68) -> inputsdlg(Prompt, title, Formats, default_answers, Options)
```

**Comment by ofloveandhate** [comment]
download and add to your path `inputsdlg` from the matlab exchange

**Comment by ofloveandhate** [comment]
use back-ticks to format code as code, please

**Comment by ofloveandhate** [comment]
polyTop assumes a single smooth bounded connected component

**Comment by tjstrunk** [comment]
polyTop _seems_ to work/give the right topology/homology computations even if I give it a decomposition gathered from bertini real.

**Comment by tjstrunk** [comment]
downloading `inputsdlg` worked! and bertini_real is also working now with the settings changed as noted above! Thanks!
