### ISSUE TITLE
Unable to run after compiling

### ISSUE THREAD

**Issue by timduff35** [ofloveandhate/bertini_real#54]
Im using Ubuntu 18.04.1 (64-bit, fresh install.) Both Bertini and bertini_real seem to compile, but only bertini seems to work---sample output come from the "Steiner surface" example in online gallery.

I gather from the output that bertini_real is trying to parse the filename as an option? In any case, the error seems to be MPI-related.

One thing I'm not sure how to check is what MPI the software are using (I think I have open mpi and mpich both somewhere on my system.) I did get this message after "make":

/usr/bin/x86_64-linux-gnu-ld: warning: libmpi.so.40, needed by //usr/local/lib/libbertini-parallel.so, may conflict with libmpi.so.20
/usr/bin/x86_64-linux-gnu-ld: warning: libmpi.so.40, needed by //usr/local/lib/libbertini-parallel.so, may conflict with libmpi.so.20

Its possible I messed up some dependencies (I installed some using linuxbrew, then apt.) But I wouldn't expect this to cause any problems after compilation.

[breal_output.txt](https://github.com/ofloveandhate/bertini_real/files/2364774/breal_output.txt)
[bertini_output.txt](https://github.com/ofloveandhate/bertini_real/files/2364775/bertini_output.txt)

**Comment by timduff35** [comment]
I think I just forgot the "-i" flag---sorry for the spam!

**Comment by ofloveandhate** [comment]
thanks for following through.  glad you found your error.
