### ISSUE TITLE
Unable to "Save Figure" for a curve in MATLAB

### ISSUE THREAD

**Issue by mgruddy** [ofloveandhate/bertini_real#57]
Error message: Reference to non-existent field 'fillpage'.

**Comment by ofloveandhate** [comment]
ah, this issue.  can you post either a screencap or text-copy of the error message, and steps to generate it?

**Comment by mgruddy** [comment]
To generate this error: After plotting a curve in MATLAB hit "Save Figure" and then the following error message appears.

"Warning: unable to complete saving for this reason:

Reference to non-existent field 'fillpage'.

Error in render_into_file>get_command (line 112)
if plot_params.fillpage

Error in render_into_file (line 96)
[evalme, final_name] = get_command(plot_params, args);

Error in bertini_real_plotter/save_routine (line 16)
		render_into_file(br_plotter.options);

Error in bertini_real_plotter/button_setup>@(varargin)br_plotter.save_routine(varargin{:}) (line 25)
[curr_y, br_plotter.buttons.save] = make_button('Save Figure', @br_plotter.save_routine, horiz_pad, vert_spacing, curr_y,
br_plotter.panels.buttons, height, width);
 
> In bertini_real_plotter/save_routine (line 20)
  In bertini_real_plotter/button_setup>@(varargin)br_plotter.save_routine(varargin{:}) (line 25) "

**Comment by ofloveandhate** [comment]
thankyou!!!  this is fixed in caa355742917d9673d4b008410ba1ebeb1341c4a.  take a pull, re-render, and you *should* be good to go.  please confirm

**Comment by mgruddy** [comment]
Yes, it now saves figures as pngs.

**Comment by ofloveandhate** [comment]
thank you.
