### ISSUE TITLE
floating point exception(core dump)

### ISSUE THREAD

**Issue by dan90210** [ofloveandhate/bertini_real#58]
while trying to run bertini_real on a cube surface, we ran into this error. to solve the error we changed `printpathmodulus : 0` in the input file to `printpathmodulus : 100`

**Comment by ofloveandhate** [comment]
ah, division by 0.  i'll do something about it.

**Comment by ofloveandhate** [comment]
fixed in ad94320ca1704c34a1e579b36b241b688075b720

may i never again cause this bug 🤖

closing
