### ISSUE TITLE
Indices Command

### ISSUE THREAD

**Issue by mgruddy** [ofloveandhate/bertini_real#59]
I'm having issues with selecting which coordinates to plot in the case of a curve of dimension >2. A bertini_real_plotter option to choose the indices would make it easier to plot projections. Thanks!

**Comment by ofloveandhate** [comment]
on it

**Comment by ofloveandhate** [comment]
should be present as of 34cf78e71af1529e0d27e4dd46a2cabbe5672e61

take a pull, and make sure it satisfies you

new feature bertini_real_plotter('indices',[1 2 3]) selects indices 1,2,3 to project on to.  repeated indices are allowed, and up-projecting of two-variable curves is not prohibited.  a surface must use three indices.

**Comment by mgruddy** [comment]
This works amazingly! Thanks so much!

**Comment by ofloveandhate** [comment]
ok, thanks
